services:
  authentication:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    ports:
      - "5174:5174"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://server:5000

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/projectexamdb
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
